version: '2'

services:

    mongodb:
        image: mongo:latest
        entrypoint: [ "/usr/bin/mongod", "--dbpath", "/data", "--journal", "--bind_ip", "0.0.0.0"]
        ports:
            - "27017:27017"

    mdo:
        image: de.jena/mdo:latest
        ports:
            - "8080-8090:8080-8090"


