<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rest" nsURI="https://jena.de/models/ibis/rest/1.0" nsPrefix="rest">
  <eClassifiers xsi:type="ecore:EClass" name="Response">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OnlineDevice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DeviceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeviceType">
    <eLiterals name="BUS"/>
    <eLiterals name="E_BUS" value="1"/>
    <eLiterals name="TRAM" value="2"/>
    <eLiterals name="TRAIN" value="3"/>
  </eClassifiers>
</ecore:EPackage>
